Calculator UI
JakariaJishan/calculator-react pull request #2
Opened 2023-02-21 20:36 UTC by JakariaJishan

- [x] Use functional components
- [x] Desing Calculator

2023-02-21 21:07 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️ ♻️ ♻️ 

Hi @JakariaJishan,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✅ You used Gitflow correctly 👍🏽
✅ Linter checks passed 👍🏽
✅ Used functional components 👍🏽
✅ The app runs with no error 👍🏽

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-02-21 21:07 UTC, AmaduKamara commented on src/components/calculator/calculator.css
> +    align-items: center; */
- [x] Let's try not to have commented code in our codebase as they make our code dirty and look unprofessional. It's a good convention to have a clean and professional codebase free from commented or unused codes. Kindly remove them 👍🏽

2023-02-21 21:07 UTC, AmaduKamara commented on src/components/calculator/Calculator.js
> +  </div>
I really love the way you styled your app, it's cool and very pleasing, but; 
- [ ] According to the design guidelines, you're required to follow the design given and to match your design with that. Please modify your styles to match the original design. The goal is to train you to work on design guidelines given for a project as that's what awaits you in your future job. 👍🏽
 
<img width="582" alt="Screenshot 2023-02-21 at 8 53 18 PM" src="https://user-images.githubusercontent.com/50941074/220457283-4679b103-ad7c-40d5-bc0a-b0916671be9d.png">

2023-02-21 21:07 UTC, AmaduKamara commented on src/components/calculator/Calculator.js
> +      <div className="division">/</div>
- [ ] For the division operator, you're to use the other sign and not the forward slash. You can use the HTML entity code `&divide;` to achieve it or you copy the sign from the project requirement and past it in your JSX 👍🏽

2023-02-22 00:32 UTC, Owusu-Desmond approved these changes
Hi @JakariaJishan , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 13:49 UTC, merged